FROM python:3.12.2-slim
LABEL maintainers="ajaybibin12@gmail.com"

ENV PYTHONUNBUFFERED 1

COPY ./requirements.txt /temp/requirements.txt
COPY ./requirements.dev.txt /temp/requirements.dev.txt
COPY ./app /app
WORKDIR /app

EXPOSE 8000

ARG DEV=false
RUN python -m venv /py && \
    /py/bin/pip install --upgrade pip && \
    apk add --update --no-cache && \
    apk add --update --no-cache postgresql-client && \
    apk add --update --no-cache --virtual .tmp-build-deps \
        build-base postgresql-dev musl-dev && \
    /py/bin/pip install -r /temp/requirements.txt && \
    if [ "$DEV" = "true" ] ; then /py/bin/pip install -r /temp/requirements.dev.txt ; fi && \
    rm -rf /temp && \
    apk del .tmp-build-deps && \
    apt-get update && apt-get install -y --no-install-recommends \
        sudo \
    && rm -rf /var/lib/apt/lists/* \
    && adduser --disabled-password --gecos '' myuser \
    && adduser myuser sudo \
    && echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
ENV PATH="/py/bin:$PATH"

USER myuser
